baseurl = "https://mrmassis.github.io/"
languageCode = "en-us"
title = "Content im Portugues"
theme = "hugo-theme-casper"
paginate = 2
Copyright = "© MRMAssis 2020"
canonifyurls = true

[params]
description = "Informações e Tutoriais de Tecnologias (e Afins ;)) em Português!"
authorlocation = "Brasil"
logo = "images/logo.png"
cover = "images/cover.png"
githubName = "mrmassis"
linkedinName = "mrmassis"
email = "marcio.miranda.assis@gmail.com"
instagramName = "mrmassis"
hideHUGOSupport = false

[[menu.main]]  # here are the buttons on the menu
name = "Home" # Button will display as "Home"
weight = 100 # the weight decides the position of the button (higher or lower)
identifier = "home"
pre = "<br />"
url = "/"

[[menu.main]]
name = "Contact"
weight = 0
identifier = "contact" # this button will refer to a markdown file named "contact" in the content folder
pre = "<br />"
url = "/contact"

[[menu.main]]
name = "Blog"
identifier = "blog" # this page will refer to a markdown file named "blog" in the content folder
pre = "<br />"
url = "/post"
weight = 40

[permalinks]
post = "/:slug/"

[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
